### PR TITLE
ported CalculateGenotypePosteriors and tests. 

### PR DESCRIPTION
**Pull request by akiezun**
Depends on https://github.com/broadinstitute/gatk/pull/1555

### CODE REVIEW

**Comment by droazen** [comment]
@akiezun Can you assign a reviewer for this one (if it's ready)?

**Comment by akiezun** [comment]
can someone update gatk public dependency?

**Comment by droazen** [comment]
Will be updated in https://github.com/broadinstitute/gatk-protected/pull/447

**Comment by droazen** [comment]
@akiezun This should be unblocked

**Comment by akiezun** [comment]
@droazen can you review? It was a straightforward port, no interesting changes as far as i remember

**Comment by akiezun** [comment]
@ldgauthier can you have a look at this - it was a straightforward port, no deep changes

**Comment by ldgauthier** [comment]
Can I get a commit for GATK 3 diff?  David says you've done that before.

**Comment by akiezun** [comment]
yes, will do

**Pull request closed without merging**
