### PR TITLE
Rev gatk-public to 4.alpha.1-53-g7734d11-SNAPSHOT

### PR DESCRIPTION
**Pull request by droazen**

### CODE REVIEW

**Comment by lbergelson** [comment]
👍 merge if tests pass

**Comment by droazen** [comment]
I just realized that this branch is not going to pass tests without the changes in https://github.com/broadinstitute/gatk-protected/pull/447. I'll keep this PR open for now as an example for @davidbenjamin of the right snapshot to use, but it should not be merged.

**Comment by davidbenjamin** [comment]
@droazen The new snapshot is in my branch, which is almost ready to merge.

**Comment by droazen** [comment]
Closing in favor of https://github.com/broadinstitute/gatk-protected/pull/447

**Pull request closed without merging**
