### PR TITLE
Adds the ability to count fragments rather than reads to the Calculate…

### PR DESCRIPTION
**Pull request by vruano**
…TargetBaseCallCoverage tool.

When average-depth is selected this means that the bases of read-pair that overlap are just counted once.
Also, instead of count reads one can now count fragments (read-pairs or a singleton read if the mate is unmapped or mapped somewhere else).

Addresses issue #295

### CODE REVIEW

**Comment by vruano** [comment]
@davidbenjamin I divided the single commit between the actual code that does the job and the testing code. That way it looks less intimidating in terms of number of lines.

**Comment by davidbenjamin** [comment]
Back to @vruano

**Comment by vruano** [comment]
I addressed your comments, please re-review.

**Comment by vruano** [comment]
@davidbenjamin

**Pull request merged**
