### PR TITLE
moved some test resources.  Addresses issue #51.

### PR DESCRIPTION
**Pull request by davidbenjamin**
@vruano Is this change what you had in mind?

### CODE REVIEW

**Comment by vruano** [comment]
Back to @davidbenjamin

**Comment by vruano** [comment]
I think you might be forgetting *.utils.* to -> *.hellbender.utils.* and also the segmenter and other test files that are placed directly under src/test/resources. 

You don't need to address them all here if you don't feel like investing time on it right now... In that case update the issue indicating what is pending.

**Comment by davidbenjamin** [comment]
@vruano I moved the other resources, too.

**Comment by vruano** [comment]
Looks good., I tried in gsa5 and test pass so I will merge it.

**Pull request merged**
