### PR TITLE
The new coverage modeller and germline CNV caller (PR preview)

### PR DESCRIPTION
**Pull request by mbabadi**
This is a preview of the upcoming PR and is meant to serve for initial assessment by the reviewers. The final PR will be issued separately in a day or two and this PR will be deleted.

Here are the following remaining tasks before the final PR:
- Further code cleanup and documentation
- More unit and integration tests (or specs for required tests along with TODO + issue #)
- Thoroughly review TODOs, make issues for them and cite issue numbers in the code

### CODE REVIEW

**Comment by samuelklee** [comment]
Looking forward to it!  If it's not too much trouble, could you organize files into separate commits in the final PR to make things a bit easier on us?

**Comment by mbabadi** [comment]
Sure @samuelklee, I can break it down. BTW, the only way I know for this is to unstage the changes, then restage in chunks and commit. Is that how you do it too?

**Comment by samuelklee** [comment]
Yeah, that's pretty much how I do it.  It's relatively painless using `tig status`.  There might be better ways to do it, though?

**Comment by mbabadi** [comment]
closing this, issuing the real pull request now.

**Pull request closed without merging**
