### PR TITLE
Removing references to ACS, RCS, and ReCapSeg, when we actually mean …

### LINKED ISSUE #253: Remove uses of RCS, ACS, etc.
Lots of uses of "ReCapSeg", "RCS", "AllelicCapSeg", "ACS", etc. are still floating around.  Update these after we finalize tool names.

### PR DESCRIPTION
**Pull request by LeeTL1220**
…GATK CNV or GATK ACNV.

This PR does NOT address ``docs/`` (see issue #303 )

Closes #253

### CODE REVIEW

**Comment by samuelklee** [comment]
found some uses of "recapseg" in NormalizeSomaticReadCounts.java

**Comment by samuelklee** [comment]
i think that's it. back to you @LeeTL1220

**Comment by LeeTL1220** [comment]
@samuelklee The usages in NormalizeReadCounts are fine.  Those are accurate.  I have pushed change to address the other one.  Back to you.

**Comment by samuelklee** [comment]
OK by me to squash and merge!

**Pull request merged**
