### PR TITLE
revup gatk public to 4.alpha.1-51-g79abe31-SNAPSHOT

### PR DESCRIPTION
**Pull request by akiezun**

### CODE REVIEW

**Comment by lbergelson** [comment]
merge when tests pass

**Comment by lbergelson** [comment]
@davidbenjamin This should include the update you needed.

**Comment by lbergelson** [comment]
@akiezun Failing I assume due to the changes that @davidbenjamin made.

**Comment by davidbenjamin** [comment]
@lbergelson That's probably true.  How about I do the revup in my branch?  The PR is almost ready to go.

**Comment by lbergelson** [comment]
@davidbenjamin Just make the same change in your build.gradle that adam made here.

**Comment by droazen** [comment]
Closing this -- we want to move to 4.alpha.1-53-g7734d11-SNAPSHOT instead

**Pull request closed without merging**
