### PR TITLE
Added tool for padding targets in a way that will not generate overlap.

### PR DESCRIPTION
**Pull request by LeeTL1220**
Fixed file extension that was causing test failure.

Updates to testing of the target padding.

Added documentation.

### CODE REVIEW

**Comment by LeeTL1220** [comment]
@achevali This should be considered live again.

**Comment by LeeTL1220** [comment]
Closes #153

**Comment by LeeTL1220** [comment]
@achevali Needless to say, the failures are due to Travis.

**Comment by LeeTL1220** [comment]
@achevali FYI... tests pass

**Comment by achevali** [comment]
Looks good, merging.

**Pull request merged**
