### PR TITLE
CNV SparkGenomeReadCounts tag doc; example WGS command

### PR DESCRIPTION
**Pull request by sooheelee**
### Questions yet to be answered:

- Who is the author of SparkGenomeReadCounts?
- Doesn't this tool need at least contig intervals, e.g. passed in via -L, to parallelize over Spark workers? 
- I will use the following opening, is it ok?
```
/**
 * Calculates read coverage on whole genome sequencing (WGS) alignments using Spark.
```

### CODE REVIEW

**Comment by sooheelee** [comment]
After discussing with Hellbender team, removed reference from the command.

**Comment by sooheelee** [comment]
Just curious if the tool spends a lot of time over synthetic regions of the genome, e.g. alpha satellite repeat arrays of GRCh38.

**Comment by achevali** [comment]
@LeeTL1220 Is there a reason that the input bam file is an optional and not a required argument?

**Comment by LeeTL1220** [comment]
@achevali How do you figure that it is optional?  @sooheelee Can you confirm that the input bam is not optional?  It seemed required to me, but I might be missing something.
@sooheelee Not sure of the answer.  We need to test on 38...

> Who is the author of SparkGenomeReadCounts?

Originally, @achevali and myself.

> Doesn't this tool need at least contig intervals, e.g. passed in via -L, to parallelize over Spark workers?

No, in fact we may want to fail if -L is passed in.  This tool creates the interval file on your behalf.

> I will use the following opening, is it ok?

Yes, fine by me.

**Comment by LeeTL1220** [comment]
@sooheelee Back to you.

**Comment by achevali** [comment]
@LeeTL1220 It's in Optional Arguments:
```--input,-I:String             BAM/SAM/CRAM file containing reads  This argument may be specified 0 or more times.  Default value: null. ```

**Comment by sooheelee** [comment]
As much as I'd love to help on your recent questions, I leave all code related questions to you coders @achevali @LeeTL1220. Might I remind you that I'm your _technical writer_ who doesn't know how to code.... If you want to change the code, please feel free to use this PR. I've made my changes to the doc portion and would like to merge this today if you guys give me the thumbs up.

**Comment by LeeTL1220** [comment]
@achevali Please file this as a bug.  Input file is required.  Thanks.

@sooheelee I'm not sure of SOP, but the doc changes look fine, except that the input file should be required.

**Comment by sooheelee** [comment]
@LeeTL1220 This goes without saying. I think the users will know that it is required without me stating the obvious despite the bug. 

The example command shows an input file.

**Pull request merged**
