### PR TITLE
Added proportion of variance explained option to SubtractCoverageComp…

### PR DESCRIPTION
**Pull request by davidbenjamin**
…onents.  Closes issue #387.

### CODE REVIEW

**Comment by davidbenjamin** [comment]
@vruano Here's another germline PR.

**Comment by vruano** [comment]
Ok back to you. 
@davidbenjamin

**Comment by davidbenjamin** [comment]
@vruano back to you.

**Comment by davidbenjamin** [comment]
Forgot to change command line arguments in the integration tests.  That was silly.  I'll fix it now.

**Comment by davidbenjamin** [comment]
@vruano It's fixed and passes locally.  *Now* you can review it.

**Comment by vruano** [comment]
Back to you @davidbenjamin.

**Comment by davidbenjamin** [comment]
@vruano done with requested changes

**Comment by vruano** [comment]
Minor comment, you can address it, squash and merge.

**Comment by vruano** [comment]
Back to you @davidbenjamin

**Comment by vruano** [comment]
Ref to the gatk public issue: https://github.com/broadinstitute/gatk/issues/1445

**Pull request merged**
