### PR TITLE
adding gradle jvm memory limit

### PR DESCRIPTION
**Pull request by lbergelson**
adding a 1gb limit to the gradle jvm to try and stop the intermittent out of memory errors

[Review on Reviewable](https://reviewable.io/reviews/broadinstitute/hellbender-protected/192)

### CODE REVIEW

**Comment by lbergelson** [comment]
@LeeTL1220 This looks like it may actually fix the problem now.  I discovered that the beta infrastructure running ubuntu 14 instead of 12 offers more ram, 7gb, and switched the build to run on that.  It seems to pass.

**Comment by lbergelson** [comment]
I'm getting a test failure:

```java
Gradle suite > Gradle test > org.broadinstitute.hellbender.tools.exome.allelefraction.AlleleFractionInitializerUnitTest.testInitialize FAILED
    java.lang.AssertionError: expected [0.0] but found [-0.02041761966572464]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:496)
        at org.testng.Assert.assertEquals(Assert.java:209)
        at org.testng.Assert.assertEquals(Assert.java:222)
        at org.broadinstitute.hellbender.tools.exome.allelefraction.AlleleFractionInitializerUnitTest.testInitialize(AlleleFractionInitializerUnitTest.java:41)
```

I don't think it's the fault of my changes though.

**Comment by lbergelson** [comment]
hmn, I get a different teset failure on rerurn:
```
 org.broadinstitute.hellbender.tools.exome.CalculateCoverageComponentsIntegrationTest.testSimpleMatrix FAILED
    java.lang.AssertionError: expected [4] but found [3]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:496)
        at org.testng.Assert.assertEquals(Assert.java:125)
        at org.testng.Assert.assertEquals(Assert.java:372)
        at org.testng.Assert.assertEquals(Assert.java:382)
        at org.broadinstitute.hellbender.utils.pca.PCAUnitTest.assertEquals(PCAUnitTest.java:201)
        at org.broadinstitute.hellbender.tools.exome.CalculateCoverageComponentsIntegrationTest.testSimpleMatrix(CalculateCoverageComponentsIntegrationTest.java:54)
```

**Comment by vruano** [comment]
Yup I have reported that problem in #239 and @davidbenjamin is looking into it.

**Comment by vruano** [comment]
That is for the one in AlleleFractionBlah... the second one I never seen it before, I guess that is for me to take care of... although test have always worked locally.

**Comment by lbergelson** [comment]
@vruano Ah, thanks for pointing that out.  

This is what happens when we can't run our test infrastructure :(  Rerunning again.  I think we should merge this even if it doesn't pass, since its now at least running the tests.

**Comment by vruano** [comment]
Ok.

**Pull request merged**
