### PR TITLE
Add binsize as a parameter for SparkGenomeReadCounts

### PR DESCRIPTION
**Pull request by achevali**

### CODE REVIEW

**Comment by LeeTL1220** [comment]
@achevali Have you tried running this on the command line with different values?  Can you just add a quick integration test that makes sure you get a different set of targets with a different binsize?

**Comment by LeeTL1220** [comment]
@achevali I see no difference.... Did you address my comment?

**Comment by achevali** [comment]
Added test for larger binsize

**Comment by achevali** [comment]
Closes #290

**Pull request merged**
