### PR TITLE
CNV PerformAlleleFractionSegmentation: Shl doc perform allele fraction segmentation

### PR DESCRIPTION
**Pull request by sooheelee**
- No example command since there is no WDL for me to reference. FYI @LeeTL1220 @achevali.
- tag doc and mention that the tumorHets file is from GetHetCoverage.

### CODE REVIEW

**Comment by sooheelee** [comment]
Nope, botched commit in attempt to rename my local branch.

**Comment by sooheelee** [comment]
Hey @LeeTL1220, is there a way to only keep the changes to PerformAlleleFractionSegmentation.java? I have other branches for the changes in the other two files.

**Comment by sooheelee** [comment]
I will redo this.

**Comment by samuelklee** [comment]
> No example command since there is no WDL for me to reference. FYI @LeeTL1220 @achevali.

There is no WDL because this tool is experimental.  In general, you should be able to put together example command lines from the integration tests for a tool.

> tag doc and mention that the tumorHets file is from GetHetCoverage.

We should probably say that the tumorHets file is from GetBayesianHetCoverage, preferably, but can also come from GetHetCoverage.

**Comment by samuelklee** [comment]
Oops, just saw that you closed this, @sooheelee!  Just so you know, you could've removed the unwanted files using git.

**Pull request closed without merging**
