### PR TITLE
Some refactoring on the segment discovery (germline caller) for a fut…

### PR DESCRIPTION
**Pull request by vruano**
…ure forkation into a discovery and genotyper tool.

### CODE REVIEW

**Comment by vruano** [comment]
Please take a look.
Next I will troduce the genotyper and try to get both tools to reuse common parts.

**Comment by vruano** [comment]
@davidbenjamin please review.

**Comment by davidbenjamin** [comment]
@vruano Looks good, just minor comments.

**Comment by vruano** [comment]
Back to @davidbenjamin

**Comment by davidbenjamin** [comment]
@vruano This is ready to squash and merge.  The places in the code where the new column descriptive statistics in `GATKProtectedMathUtils` can be applied are:

`TangentNormalizer::composeTangentNormalizationInputMatrix` (line 230)
`NormalizeSomaticReadCountsIntegrationTest::assertPreTangentNormalizedValues` (line 482)

Also, in `ReadCountCollection::normalizeByColumnAverages` for the case where weighting by target length is not chosen you could use the new `columnMeans` method and thereby simplify the `if. . . else`

**Comment by davidbenjamin** [comment]
@vruano Whoops, I forgot to reassign you.

**Comment by vruano** [comment]
@davidbenjamin 
please review last commit, that propagates the use of columnMeans to the locations you indicated.

**Comment by davidbenjamin** [comment]
@vruano This is good to go.

**Pull request merged**
