### PR TITLE
Jenkins docker

### PR DESCRIPTION
**Pull request by davidbernick**
@LeeTL1220 I probably did the PR wrong (did it against master). Let me know a better way.

### CODE REVIEW

**Comment by davidbernick** [comment]
(this also serves as the autotesting for gatk-protected with PRs)

**Comment by davidbernick** [comment]
eval test please

**Comment by davidbernick** [comment]
eval this please

**Comment by davidbernick** [comment]
eval test please

**Comment by davidbernick** [comment]
eval test please

**Comment by davidbernick** [comment]
eval test please

**Comment by davidbernick** [comment]
eval test please

**Comment by davidbernick** [comment]
eval test please

**Comment by davidbernick** [comment]
eval test please

**Comment by LeeTL1220** [comment]
@davidbernick Do you need me to do something here?  It is still failing.

**Comment by LeeTL1220** [comment]
@davidbernick Or is this just to kick off the jenkins?

**Comment by davidbernick** [comment]
eval test please

**Pull request closed without merging**
