### PR TITLE
Do not emit GVCF block definitions in the header

### PR DESCRIPTION
**Pull request by ronlevine**
Implements #696 .

### CODE REVIEW

**Comment by ronlevine** [comment]
@vdauwera Please review.

**Comment by vdauwera** [comment]
This looks fine to me. 

@droazen do you feel this needs to be quarantined pending the tie-out results too or is it ok to merge? It only affects headers.

**Comment by ronlevine** [comment]
@droazen Ping.

**Comment by droazen** [comment]
@vdauwera @ronlevine I defer to @lbergelson on this, since he is responsible for coordinating the tie-out of GenotypeGVCFs.

**Comment by lbergelson** [comment]
👍  to merging.  Headers aren't going to be an exact match anyway.

**Pull request merged**
