### PR TITLE
docs for using PoN in allele fraction model

### PR DESCRIPTION
**Pull request by davidbenjamin**
Very brief addition to ACS-methods.pdf showing how one can obtain SNP-by-SNP priors on allelic bias from a PoN just by recycling extant code from the allele fraction model.  I have been assigning this sort of PR to @samuelklee, but would @LeeTL1220 or @vruano like a turn to look at some math?

### CODE REVIEW

**Comment by samuelklee** [comment]
I'm a bit swamped at the moment and still owe you a PR....@LeeTL1220 or @vruano should feel free to take a look in the meantime!

**Comment by davidbenjamin** [comment]
@vruano This is for you, should be quick.

**Comment by vruano** [comment]
Back to @davidbenjamin

**Comment by davidbenjamin** [comment]
@vruano This commit does what you asked for.

**Comment by vruano** [comment]
Good job, tests are failing due to old issues already fixed in master. Merging...

**Pull request merged**
