### PR TITLE
Germline docs, closes issue #403

### PR DESCRIPTION
**Pull request by davidbenjamin**
@vruano could you take a look at this summary of the current model?

### CODE REVIEW

**Comment by vruano** [comment]
Just one misunderstanding.
Back to you @davidbenjamin

**Comment by davidbenjamin** [comment]
@vruano I should also note that the change in PR #389 is not in the master branch of the eval repo but is in the `db_improvements` branch that will be a PR very soon.

**Comment by davidbenjamin** [comment]
Oh wait, it's already a PR.  Whoops!

**Comment by vruano** [comment]
David what you want me to do? are you supposed to push some amenent

**Pull request merged**
