### PR TITLE
Scatter M2 over pairs and intervals. Closes #841.

### LINKED ISSUE #841: scatter Mutect over pairs and intervals
... by creating a single tumor-normal pair workflow that scatters over intervals and calling it as a sub-workflow from a wdl that scatters over pairs.

### PR DESCRIPTION
**Pull request by davidbenjamin**
@takuto can you review this after the two-pass PR (this contains those commits, and I will bring any changes you suggest for that PR in this one)?  I basically copied your approach from the palantir PR.

### CODE REVIEW

**Comment by davidbenjamin** [comment]
And by @takuto I mean @takutosato.

**Comment by takutosato** [comment]
If you don't oppose to the renaming the single-pair wdl back to 'mutect2.wdl', I can make the change and merge the branch. Don't want to waste your time for my arbitrary personal preference.

**Comment by davidbenjamin** [comment]
@takutosato You arbitrary preference makes sense to me, and in any case there was a non-trivial rebase.  Back to you when tests pass.

**Comment by takutosato** [comment]
@davidbenjamin looks good. The tests keep failing though. I restarted it the second time just now. Hopefully this time they will pass.

**Comment by davidbenjamin** [comment]
@takutosato probably some rebase thing; I'll figure it out.

**Comment by davidbenjamin** [comment]
Or, apparently, a Travis thing.  I'll merge after running the wdl on the Broad server.

**Pull request merged**
