### PR TITLE
Docs for proposed HMM-based segmentation

### PR DESCRIPTION
**Pull request by davidbenjamin**
Like the other docs PR no need for review just yet.

### CODE REVIEW

**Comment by davidbenjamin** [comment]
@mbabadi Could you take a look at these notes?

**Comment by mbabadi** [comment]
Definiely, sorry for slacking about it :)
On Apr 15, 2016 6:09 PM, "David Benjamin" <notifications@github.com> wrote:

@mbabadi <https://github.com/mbabadi> Could you take a look at these notes?

—
You are receiving this because you were mentioned.

Reply to this email directly or view it on GitHub
<https://github.com/broadinstitute/gatk-protected/pull/422#issuecomment-210665146>

**Comment by davidbenjamin** [comment]
@mbabadi It's not slacking if I hadn't asked you about it!

**Comment by davidbenjamin** [comment]
. . . which I hadn't until now.

**Comment by davidbenjamin** [comment]
By the way, I would appreciate not just a check of correctness but also a critical eye toward the use of an HMM for this.

**Comment by davidbenjamin** [comment]
@mbabadi I just pushed a revision that I believe is mathematically equivalent but eliminates the need to explicitly augment the hidden state with a binary indicator of memory loss.  This will make the code much more transparent.

**Comment by davidbenjamin** [comment]
Closed by PR #596.

**Pull request closed without merging**
