### PR TITLE
connect PairHMMNativeArguments args to HaplotypeCaller

### PR DESCRIPTION
**Pull request by lbergelson**
Adding a new `PairHmmNativeArgumentCollection` to `LikelihoodArgumentCollection`.  This allows the precision and number of threads to use for PairHmms to be passed in from the command line.

### CODE REVIEW

**Comment by lbergelson** [comment]
@droazen Here's the glue.

**Comment by lbergelson** [comment]
@davidbenjamin Did you make any changes in public that would affect allele-specific annotations?  I'm seeing a test failure here, but I'm pretty sure it's not due to my changes.  I've run locally gatk-protected f573d7ea5 built on top of https://github.com/broadinstitute/gatk/commit/64661b5f4 which is before any of the pairhmm changes went into either repo and I still see the test failure.

**Comment by droazen** [comment]
@lbergelson Can we do the rev of the public dependency separate from this PR to disambiguate?

**Comment by davidbenjamin** [comment]
@lbergelson I made some changes to annotations in PRs broadinstitute/gatk#2239 and broadinstitute/gatk#2185, but those went into public well before the last rev.

**Comment by lbergelson** [comment]
@davidbenjamin Then you're off the hook then... Oh well, I was hoping it would be something obvious.  

@droazen Good idea.  Are you doing that since you've assigned this to yourself?

**Comment by droazen** [comment]
@lbergelson I was assigning myself as reviewer, but happy to create the separate PR to rev the public dependency.

**Comment by droazen** [comment]
Am looking at that HaplotypeCaller test failure now

**Comment by droazen** [comment]
The annotations missing are precisely those that implement `StandardHCAnnotation`

**Comment by droazen** [comment]
OK, I think I've got it -- it's a side effect of commit 50cb7f70a28e1b7f8821ecfd2d2665aefaaae54d "Change list argument behavior to replace". Should be an easy fix!

**Comment by droazen** [comment]
I've opened https://github.com/broadinstitute/gatk-protected/pull/826. That should go in first, since it fixes the HC tests, then this branch should be rebased on top of it. Note that you'll have to remove a few lines of temporary code in `PairHMMLikelihoodCalculationEngine` when you do the rebase.

**Comment by droazen** [comment]
@lbergelson Can this be closed?

**Comment by lbergelson** [comment]
Closing because these changes were incorporated into #998

**Pull request closed without merging**
