### PR TITLE
Closes #353 and rewrote tests to fail with the old code.

### LINKED ISSUE #353: CombineReadCounts fails when targets' chromosome order is 1, 2 . . . 23
`HashedListTargetCollection` is traversed in the lexicographical order of contigs because its `sortedIntervals` field is initialized via `IntervalUtils.LEXICOGRAPHICAL_ORDER_COMPARATOR`.  This is the order that `CombineReadCounts` uses when it calls `targets.targets()`.  Therefore, if the targets are in the order 1, 2, 3 . . . 23, it goes through chromosome 1, then does `seekTarget` to chromosomes 11, 12, 13, 14 . . . 19.  Next `seekTarget` looks for the first target in chromosome 2, which fails because it jumped past 2, 3, 4 . . . 9 in order to reach chromosome 11 after chromosome 1.

To reproduce this error quickly, run `CombineReadCountsIntegrationTest` but replace `TEST_CHR = new String[] { "1", "2", "3"}` with `TEST_CHR = new String[] { "1", "2", "11"}`.  Note also that it passes for {"1", "11", "2"}.

The root of the issue is that there are two inconsistent target orderings, the lexicographically sorted order of `HashedListTargetCollection` and the order of the original targets file.

### PR DESCRIPTION
**Pull request by davidbenjamin**
@vruano do you have time to review this?

### CODE REVIEW

**Comment by vruano** [comment]
Yup.

**Comment by vruano** [comment]
Finish with reviews. Check my code proposal. If you think it makes things easier to understand take it on board otherwise you can commit the code as it is. Up to you.

**Comment by davidbenjamin** [comment]
@vruano I like your simplification.  The previous code works even if the input files don't have the same targets, as long as they contain the *specified* targets in the same order.  The proposed code requires all targets, even those not used, to be shared by all inputs.  Are you okay with this?

**Comment by vruano** [comment]
Yes I am, is there any reason why this would not be the case?

**Comment by davidbenjamin** [comment]
@vruano changes based on your suggestion.

**Comment by davidbenjamin** [comment]
@vruano It's a lot prettier now.

**Comment by vruano** [comment]
Well done rebase, squash and merge when test pass again.

**Pull request merged**
